maintainer        "Mike Scherbakov, Aleksei Kornev"
maintainer_email  "mihgen@gmail.com, aleksei.kornev@gmail.com"
license           "Apache 2.0"
description       "Installs hadoop"
version           "0.1"
depends     "ssh_known_hosts"
depends     "java6"
depends     "keepalived"
depends     "glusterfs"
